# Generated by Django 4.0.4 on 2022-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./static/blank-profile-picture-973460_640.png', upload_to='post/'),
        ),
    ]
