# Generated by Django 4.0.4 on 2022-07-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelation',
            old_name='followers',
            new_name='follower',
        ),
    ]
